name: Test Vars context test
run-name: Run Vars context test

on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello VAR_TEST"
        run: echo "Hello ${{ vars.VARS_TEST }}"
